# # This file is a template, and might need editing before it works on your project.
# # To contribute improvements to CI/CD templates, please follow the Development guide at:
# # https://docs.gitlab.com/ee/development/cicd/templates.html
# # This specific template is located at:
# # https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Pages/HTML.gitlab-ci.yml

# # Full project: https://gitlab.com/pages/plain-html
# pages:
#   stage: deploy
#   environment: production
#   script:
#     - mkdir .public
#     - cp -r ./* .public
#     - rm -rf public
#     - mv .public public
#   artifacts:
#     paths:
#       - public
  # rules:
  #   - if: $CI_COMMIT_BRANCH == "master" && $CI_DEFAULT_BRANCH

# This is a basic example of a .gitlab-ci.yml file for a Node.js project

# Define stages that will be used in the pipeline
image: node:12.x

stages:
  - build
  - run

first-job:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules
  only:
    - $CI_COMMIT_BRANCH == "master" && $CI_DEFAULT_BRANCH

second-job:
  stage: run
  script:
    - npm run start
    - node test.js
  artifacts:
    paths:
      - node_modules/
  only:
    - $CI_COMMIT_BRANCH == "master" && $CI_DEFAULT_BRANCH
